Repository DataDog/riot, pull requests merged in 2021-03, with the labels that each got.

#116 feat: add option to skip missing interpreters
  releasenotes/notes/feature-skip-missing-a032464fbeafdc52.yaml
  riot/cli.py
  riot/riot.py
  tests/test_cli.py
Labels: automerge

#118 Only run CI on pull request or pushes to main branch
  .github/workflows/main.yml
Labels: automerge, no-changelog

#120 test: remove useless test file
  tests/test_cli.py
Labels: automerge, no-changelog

#121 ci: do not set LANG
  riotfile.py
Labels: automerge, no-changelog

#125 ci(mergify): simplify merging condition
  .mergify.yml
Labels: no-changelog

#126 ci(mypy): enable more checks
  riot/riot.py
  setup.cfg
Labels: no-changelog

#119 fix: make sure venv is passed to subprocess.run
  riot/riot.py
  tests/test_cli.py
Labels: automerge, no-changelog

#127 refactor: move run_cmd_venv to Session and always export some env var
  riot/riot.py
Labels: no-changelog

#129 fix(riot): do not copy symlink target
  riot/riot.py
Labels: no-changelog
